### ISSUE TITLE
Last element in dl_docs leads to error "Error response for subscription "{'type': 'timelineDetailV2'"

### ISSUE THREAD

**Issue by popopirat** [pytr-org/pytr#232]
**Description of the bug**
When downloading using the dl_docs command, the first n-1 items appear to be registered correctly. However the last element leads to an error 
**To Reproduce**

1. Ran the command `pytr dl_docs`
2. See error:
2025-07-18 12:23:40,636 - api - DEBUG - Received message: '42 C'
2025-07-18 12:23:40,636 - api - DEBUG - Received message: '486 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-18 12:23:40,636 - api - ERROR - Received error message: '486 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-18 12:23:40,636 - api - DEBUG - Unsubscribing: 486

3. No files are downloaded
**Expected behavior**
All pdfs are downloaded
**Error log**

```
[Success for 1-467]
2025-07-18 12:23:40,634 - timeline - INFO - 467/468:  $USER -- Fertig - 2025-MM-DDTHH:MM:SS
2025-07-18 12:23:40,635 - dl - DEBUG - File /$myPATH/Fertig.pdf already in queue. Append document id aaaaaaaaaaaa-bbbbb-ccccc-ddddddddddddddd...
2025-07-18 12:23:40,635 - dl - DEBUG - Added /$myPATH/.pdf to queue
2025-07-18 12:23:40,636 - api - DEBUG - Received message: '42 C'
2025-07-18 12:23:40,636 - api - DEBUG - Received message: '486 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-18 12:23:40,636 - api - ERROR - Received error message: '486 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-18 12:23:40,636 - api - DEBUG - Unsubscribing: 486
2025-07-18 12:23:40,636 - dl - ERROR - Error response for subscription "{'type': 'timelineDetailV2', 'id': '6ed53082-c612-4a0d-ae49-853c46e5f0c1'}". Re-subscribing...
2025-07-18 12:23:40,637 - api - DEBUG - Subscribing: 'sub 487 {"type": "timelineDetailV2", "id": "6ed53082-c612-4a0d-ae49-853c46e5f0c1"}'
2025-07-18 12:23:40,693 - api - DEBUG - Received message: '487 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-18 12:23:40,694 - api - ERROR - Received error message: '487 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-18 12:23:40,694 - api - DEBUG - Unsubscribing: 487`

This goes on forever.

```

**Environment**

- OS: Ubuntu 22.04
- pytr version: latest (v0.4.2)

**Additional context**
-

**Comment by RealCLanger** [comment]
Likely a duplicate of #205 and #173

**Comment by RealCLanger** [comment]
I just published a new pytr version (v0.4.3). Can you reproduce the issues with that version, too? I would think so...

**Comment by popopirat** [comment]
> I just published a new pytr version (v0.4.3). Can you reproduce the issues with that version, too? I would think so...

If that new Version is used with the command
` uvx --with git+https://github.com/pytr-org/pytr.git pytr -v debug --debug-logfile debug_pytr.log  dl_docs .
`
`uvx pytr@latest -v debug  --debug-logfile debug_pytr.log dl_docs .
`

then yes, error persists for both commands:
**Error log**

```2025-07-20 11:50:29,949 - api - DEBUG - Received message: '97 C'
2025-07-20 11:50:29,951 - api - DEBUG - Received message: '486 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-20 11:50:29,951 - api - ERROR - Received error message: '486 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-20 11:50:29,951 - api - DEBUG - Unsubscribing: 486
2025-07-20 11:50:29,957 - dl - ERROR - Error response for subscription "{'type': 'timelineDetailV2', 'id': '6ed53082-c612-4a0d-ae49-853c46e5f0c1'}". Re-subscribing...
2025-07-20 11:50:29,958 - api - DEBUG - Subscribing: 'sub 487 {"type": "timelineDetailV2", "id": "6ed53082-c612-4a0d-ae49-853c46e5f0c1"}'
2025-07-20 11:50:30,015 - api - DEBUG - Received message: '487 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-20 11:50:30,016 - api - ERROR - Received error message: '487 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-20 11:50:30,016 - api - DEBUG - Unsubscribing: 487
2025-07-20 11:50:30,019 - dl - ERROR - Error response for subscription "{'type': 'timelineDetailV2', 'id': '6ed53082-c612-4a0d-ae49-853c46e5f0c1'}". Re-subscribing...
2025-07-20 11:50:30,020 - api - DEBUG - Subscribing: 'sub 488 {"type": "timelineDetailV2", "id": "6ed53082-c612-4a0d-ae49-853c46e5f0c1"}'
2025-07-20 11:50:30,071 - api - DEBUG - Received message: '488 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-20 11:50:30,072 - api - ERROR - Received error message: '488 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
2025-07-20 11:50:30,072 - api - DEBUG - Unsubscribing: 488
2
´´´

**COMMENTS**


> Likely a duplicate of [#205](https://github.com/pytr-org/pytr/issues/205) and [#173](https://github.com/pytr-org/pytr/issues/173)

I see, looks similar!

**Comment by davidlinse** [comment]
hi, i can confirm the issue with the latest version `v0.4.3`. 
any news on this ?

**Comment by RealCLanger** [comment]
It's on my list. Unfortunately I can not reproduce it with my account so I need to check the coding and add some more tracepoints.

**Comment by cellradar** [comment]
I got the same issue. Just tell me, if I can help with logs etc.

**Comment by Alternativend** [comment]
Same here since they have introduced PrivEquity invests.

**Comment by JBH168** [comment]
I have the same error. For me, it always happens directly after 

`20:13:33  998/1532: BMW (Vz) -- Limit-Buy-Order storniert - 2020-06-12T07:01:34`
(note: other transactions can take this place instead, but it's always after 998/1532)

and then just keeps alternating between these two versions (with updated timestamps and error message numbers):
```
20:13:33 Received error message: '1040 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
20:13:33 Error response for subscription "{'type': 'timelineDetailV2', 'id': '688f8359-9ba0-4a23-9cb6-548d79bdf51f'}". Re-subscribing...
```
```
20:13:33 Received error message: '1041 E {"errors":[{"errorCode":"NOT_FOUND","errorField":null,"errorMessage":"Could not find resource","meta":{"source":"PLATFORM"}}]}'
20:13:33 Error response for subscription "{'type': 'timelineDetailV2', 'id': '19f46117-50a2-4aa9-8415-08010686899e'}". Re-subscribing...
```

Let me know if I can help with any more information.

**Comment by RealCLanger** [comment]
I'm working on some kind of fuse for the re-subscriptions. Unfortunately it occurs on occasionally for me so it's difficult to recreate. But I have a prototype ready for a fix. Will post it soon.

**Comment by RealCLanger** [comment]
With the latest changes, this error should be gone. Please let me know if otherwise.
